### ISSUE TITLE
Provide Certificate Values as a Secret Reference

### ISSUE THREAD

**Issue by ssdowdavalon** [confluentinc/confluent-kubernetes-examples#13]
I am using the helm charts and I would like to be able to provide the `kafka.tls.privkey`, `kafka.tls.fullchain` and `kafka.tls.cacerts` as secret references (where the certs are provided by cert-manager).  Right now this has to be a multi-step process to deploy (get certs, extract them into `values.yaml`, finally create confluent components).  Allowing these to be provided via secrets would make the process simpler.

**Comment by ptyagii** [comment]
hey @ssdowdavalon you can use the secret feature in [Confluent for Kubernetes ](https://docs.confluent.io/operator/current/overview.html), check the following links: 

- https://docs.confluent.io/operator/current/co-network-encryption.html#configure-auto-generated-tls-certificates
- https://docs.confluent.io/operator/current/co-network-encryption.html#configure-user-provided-tls-certificates 

You can create the secrets and configure it in the component CR as follows: 

```
spec:
  tls:
    secretRef: kafka-tls
```

You may also check the examples: 

- https://github.com/confluentinc/confluent-kubernetes-examples/blob/master/security/production-secure-deploy/confluent-platform-production.yaml#L16 
- https://github.com/confluentinc/confluent-kubernetes-examples/tree/master/security/production-secure-deploy 
- https://github.com/confluentinc/confluent-kubernetes-examples/tree/master/security/secure-authn-encrypt-deploy#deploy-configuration-secrets

**Comment by MosheBlumbergX** [comment]
Stale issue, closing
