### ISSUE TITLE
Istio ingress gateway to access Kafka examples?

### ISSUE THREAD

**Issue by perezjasonr** [confluentinc/confluent-kubernetes-examples#137]
Hello, I'm trying to set up confluent platform and make kafka accessible via istio's ingress gateway, but I can't get it to work and I cannot find anywhere in documentation or submitted issues of anyone attempting to make it work behind istio ingress gateway.

I get these messages from fluentbit with the kafka conf set to send to brokers via the value:

```
    kafka:
      enable: true
      brokers: "kafka.mydomain.com:80"
      topics: ks-log
```

for reference it is taken from here

https://github.com/fluent/fluent-operator/blob/master/charts/fluent-operator/values.yaml#L124

here are the messages I get

```
[2022/06/17 19:29:01] [ warn] [output:kafka:kafka.0] message delivery failed: Local: Message timed out
[2022/06/17 19:29:01] [ warn] [output:kafka:kafka.0] message delivery failed: Local: Message timed out
[2022/06/17 19:29:01] [ warn] [output:kafka:kafka.0] message delivery failed: Local: Message timed out
[2022/06/17 19:29:01] [ warn] [output:kafka:kafka.0] message delivery failed: Local: Message timed out
[2022/06/17 19:29:01] [ warn] [output:kafka:kafka.0] message delivery failed: Local: Message timed out
[2022/06/17 19:29:01] [error] [output:kafka:kafka.0] fluent-bit#producer-1: [thrd:app]: fluent-bit#producer-1: kafka.mydomain.com:80/bootstrap: Disconnected while requesting ApiVersion: might be caused by incorrect security.protocol configuration (connecting to a SSL listener?) or broker version is < 0.10 (see api.version.request) (after 9999ms in state APIVERSION_QUERY, 3 identical error(s) suppressed)
[2022/06/17 19:29:04] [error] [output:kafka:kafka.0] fluent-bit#producer-1: [thrd:kafka.mydomain.com:80/bootstrap]: 1/1 brokers are down
[2022/06/17 19:29:11] [error] [filter:kubernetes:kubernetes.1] kubelet upstream connection error
[2022/06/17 19:29:15] [ info] [output:kafka:kafka.0] fluent-bit#producer-1: [thrd:kafka.mydomain.com:80/bootstrap]: kafka.9tlat6vp.wooden-proton.com:80/bootstrap: Disconnected while requesting ApiVersion: might be caused by incorrect security.protocol configuration (connecting to a SSL listener?) or broker version is < 0.10 (see api.version.request) (after 10001ms in state APIVERSION_QUERY, 3 identical error(s) suppressed)
[2022/06/17 19:29:15] [error] [output:kafka:kafka.0] fluent-bit#producer-1: [thrd:kafka.mydomain.com:80/bootstrap]: 1/1 brokers are down
[2022/06/17 19:29:21] [error] [filter:kubernetes:kubernetes.1] kubelet upstream connection error
[2022/06/17 19:29:26] [error] [output:kafka:kafka.0] fluent-bit#producer-1: [thrd:kafka.mydomain.com:80/bootstrap]: 1/1 brokers are down
[2022/06/17 19:29:31] [error] [filter:kubernetes:kubernetes.1] kubelet upstream connection error
[2022/06/17 19:29:37] [error] [output:kafka:kafka.0] fluent-bit#producer-1: [thrd:kafka.mydomain.com:80/bootstrap]: 1/1 brokers are down
[2022/06/17 19:29:41] [error] [filter:kubernetes:kubernetes.1] kubelet upstream connection error
[2022/06/17 19:29:48] [ info] [output:kafka:kafka.0] fluent-bit#producer-1: [thrd:kafka.mydomain.com:80/bootstrap]: kafka.9tlat6vp.wooden-proton.com:80/bootstrap: Disconnected while requesting ApiVersion: might be caused by incorrect security.protocol configuration (connecting to a SSL listener?) or broker version is < 0.10 (see api.version.request) (after 10000ms in state APIVERSION_QUERY, 3 identical error(s) suppressed)
[2022/06/17 19:29:48] [error] [output:kafka:kafka.0] fluent-bit#producer-1: [thrd:kafka.mydomain.com:80/bootstrap]: 1/1 brokers are down
[2022/06/17 19:29:51] [error] [filter:kubernetes:kubernetes.1] kubelet upstream connection error
```

here are my istio objects:

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: confluent-gateway
  namespace: confluent
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - kafka.mydomain.com
    - control.mydomain.com
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: control-v-service
  namespace: confluent
spec:
  hosts:
  - control.mydomain.com
  gateways:
  - confluent-gateway
  http:
  - route:
    - destination:
        host: controlcenter
        port:
          number: 9021
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kafka-v-service
  namespace: confluent
spec:
  hosts:
  - kafka.mydomain.com
  gateways:
  - confluent-gateway
  http:
  - route:
    - destination:
        host: kafka
        port:
          number: 9092
```

It is noteworthy that this works to get me into the control center following this model, but kafka brokers dont seem to be happy with the attempt. I also tried to change 9092 to 9097 (i believe in the quickstart it uses the internal port) but both have the same result.

Since confluent for kubernetes is obviously trying to work with Kubernetes I think it might be good to have an example in these kubernetes examples for istio ingress to work since Istio is so popular. 

I'm not sure what else to try here. I thought maybe try looking at security.protocol configuration, but in the quickstart the client it set to plaintext, and according to librdkafka, which is what fluentbit uses 

https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

plaintext is the default so I dont think its because its trying to SSL or anything like that.

**Comment by perezjasonr** [comment]
So I tried these instructions and wondering if fluentbit/fluentd which is very commonly used in k8s, as is istio, might not be compatible?

fluent uses librdkafka, is that compatible with the CFK kafka brokers? wondering if thats the issue. librdkafka has options such as ssl verify cert false, and it has just a regular ca/cert/key setup, whereas the docs have the keytool and truststore instructions im wondering if it must be a truststore/keytool setup for the client.

**Comment by perezjasonr** [comment]
Btw wondering if my suspicion might be slightly confirmed here:

https://docs.confluent.io/platform/current/kafka/encryption.html

only keystore and truststore are shown, i feel like this implies a normal key/cert/ca will not be accepted.
otherwise i cannot find an extensive list of properties showing the options.

**Comment by OneCricketeer** [comment]
Librdkafka (and Java clients) do support ca certificate files

https://github.com/edenhill/librdkafka/blob/master/examples/openssl_engine_example.cpp#L192

**Comment by perezjasonr** [comment]
> Librdkafka (and Java clients) do support ca certificate files
> 
> https://github.com/edenhill/librdkafka/blob/master/examples/openssl_engine_example.cpp#L192
> 
> > cannot find an extensive list of properties showing the options
> 
> https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

Right but youre showing librdkafka's side. I'm saying and showing the confluent side doesn't show it. I literally linked that exact configuration.md in my original post. In fact that list proves my point. theres no truststore anywhere there.

Have you ever gotten CFK to work with fluent bit or librdkafka using the example here:

https://github.com/confluentinc/confluent-kubernetes-examples/tree/master/networking/external-access-static-host-based#appendix-istio-gateway

**Comment by OneCricketeer** [comment]
I haven't used this operator, but ignoring Kubernetes completely, here's a wiki page for translating JKS broker configurations into librdkafka client certificates, which as mentioned in your other issue, should be able to be passed as-is into fluentbit configuration using `rdkafka.{property}` 

https://github.com/edenhill/librdkafka/wiki/Using-SSL-with-librdkafka

**Comment by OneCricketeer** [comment]
In any case, Kafka isn't an HTTP protocol, so configuring Istio to literally have `protocol: HTTP` seems like it wouldn't work.

**Comment by perezjasonr** [comment]
> In any case, Kafka isn't an HTTP protocol, so configuring Istio to literally have `protocol: HTTP` seems like it wouldn't work.

thats from before I found the official example, I then followed the example linked from confluent to try this which uses protocol: tls


> I haven't used this operator, but ignoring Kubernetes completely, here's a wiki page for translating JKS broker configurations into librdkafka client certificates, which as mentioned in your other issue, should be able to be passed as-is into fluentbit configuration using `rdkafka.{property}`
> 
> https://github.com/edenhill/librdkafka/wiki/Using-SSL-with-librdkafka

this uses a ca, which I tried.

```
# CA certificate file for verifying the broker's certificate.
ssl.ca.location=ca-cert
```

again, ive gotten the example I linked set up. I got the producer cli to work and produce to the topic probably because that can take a truststore. What I couldn't get to work was librdkafka/fluent bit. As we can see in the configuration.md, there is no truststore. on the confluent side, there doesn't appear to be a "ca" option.

**Comment by OneCricketeer** [comment]
Unclear what you mean need to be configuring extra on the "Confluent side". 

You say you have a CLI working? That's a Java client like `kafka-console-producer` or a librdkafka based client like `kcat`?

**Comment by perezjasonr** [comment]
> Unclear what you mean by needing to configure anything extra on the "Confluent side".
> 


I'm talking about the official confluent docs for example in their encryption section:

> 
Configure the password, truststore, and keystore in the server.properties file of every broker. Since this stores passwords directly in the broker configuration file, it is important to restrict access to these files using file system permissions.

they show some properties and theres a truststore, unsurprisingly, never a "ca" option. If there is one, I'm still looking for it.

furthermore, I found more examples of secrets being created using a ca, but in the end the client still uses a truststore, and I think the docs suggest that even if you use cert secrets confluent converts it to a truststore/keystore/jks

> You say you have a CLI working? That's a Java client like `kafka-console-producer` or a librdkafka based client like `kcat`?

I used the official kafka-console-producer yeah exactly in the example. But thats not realistic, I then wanted to use something many kubernetes folks are expected to use, fluentbit and without the truststore option I had to try the librdkafka CA property, this didn't work.

So if anyone has gotten CFK to work with librdkafka id love to hear a success story. Right now I'm of the impression they arent compatible.

**Comment by perezjasonr** [comment]
Heres an example of what I'm talking about:

https://github.com/confluentinc/confluent-kubernetes-examples/tree/master/security/autogenerated-tls_only

> Create the kafka.properties file in $TUTORIAL_HOME with the above. The auto-generated certs will create a truststore and mount it on all Confluent Platform component pods at /mnt/sslcerts/truststore.jks. The default truststore password is mystorepassword.

So a CA is used in this example but in the end a truststore is created. the example client then uses a truststore of course.
I do not believe you can follow this example, then replace the client section with librdkafka

**Comment by perezjasonr** [comment]
ill try this extraction bit then, its at least a new route to take.
Before, I had just provided the CA cert in the usual pki fashion. most kubernetes services ask for a ca to trust. but as said before It didn't seem to like it. Perhaps extracting it after the fact might result in success.

**Comment by perezjasonr** [comment]
got it working see the librdkafka issue

https://github.com/edenhill/librdkafka/issues/3889

I didnt end up extracing the pem from the jks file, but that might also work if someone wants to try it. and I do think it was a good suggestion.
