### ISSUE TITLE
How to connect to kafka in openshift

### ISSUE THREAD

**Issue by shichw** [confluentinc/confluent-kubernetes-examples#158]
I have enabled routing for kafka with a custom certificate, but I can't connect to kafka, can you help me

**Comment by OneCricketeer** [comment]
Are you using this Operator?

I ask because RedHat supports Strimzi on OpenShift and documents how to use their Route resources for accessing Kafka

**Comment by Shi2020** [comment]
Thank you. I have found a solution to this problem. This issue can be closed.
