### ISSUE TITLE
There is no way to not use nodePortOffset?

### ISSUE THREAD

**Issue by arezvani** [confluentinc/confluent-kubernetes-examples#213]
Hi,
I want to deploy confluent platform and kafka has external access with nodeport type. nodePortOffset is required and all N+1 nodeports shouldn't be already allocated by another app. Is there any way to automatically choose the ports not already allocated and they don't be sequential.

**Comment by MosheBlumbergX** [comment]
Hi @arezvani , check out the nodePort under the servicePorts, you can pass a range in there. 

https://docs.confluent.io/operator/current/co-api.html#tag/Kafka
