### ISSUE TITLE
add a note for autogeneratedcerts scenario 

### ISSUE THREAD

**Issue by ptyagii** [confluentinc/confluent-kubernetes-examples#22]
Encountered secret missing error when using [confluent-platform-production-autogeneratedcerts.yaml](https://github.com/confluentinc/confluent-kubernetes-examples/blob/master/security/production-secure-deploy/confluent-platform-production-autogeneratedcerts.yaml) file to deploy CP: 

Output from `kubectl get events` 
 
`23s         Warning   KeyInSecretRefIssue      zookeeper/zookeeper                              secret ca-pair-sslcerts missing in namespace confluent. Please create a secret object accordingly
`

Created a `ca-pair-sslcerts` secret following the [link](https://github.com/confluentinc/confluent-kubernetes-examples/tree/master/security/secure-authn-encrypt-deploy#provide-a-root-certificate-authority) resolved the issue. 

It'd be helpful to add a note for `autogeneratedcerts` scenario in the `security/production-secure-deploy/README.rst`

**Comment by MosheBlumbergX** [comment]
https://github.com/confluentinc/confluent-kubernetes-examples/pull/30

**Comment by rohit2b** [comment]
This will be fixed with PRs #30 and #32

**Comment by MosheBlumbergX** [comment]
both merged now
