### ISSUE TITLE
namespace step missing for production-recommended-secure-setup 

### ISSUE THREAD

**Issue by ptyagii** [confluentinc/confluent-kubernetes-examples#25]
Can we please add a step to create a namespace and setting the namespace for the k8s context on [production-recommended-secure-setup page](https://github.com/confluentinc/confluent-kubernetes-examples/tree/master/security/production-secure-deploy#production-recommended-secure-setup)? 

- kubectl config set-context --current --namespace confluent
- https://docs.confluent.io/operator/current/co-quickstart.html#step-1-create-a-namespace

Another suggestion would be to add the `--namespace <namespace>` to the [commands](https://github.com/confluentinc/confluent-kubernetes-examples/tree/master/security/production-secure-deploy#appendix-update-authentication-users) used on [secure setup page](https://github.com/confluentinc/confluent-kubernetes-examples/tree/master/security/production-secure-deploy#production-recommended-secure-setup).

**Comment by rohit2b** [comment]
This has been addressed with PR #30
