### ISSUE TITLE
secretRefs missing using confluent-platform-production-mtls.yaml 

### ISSUE THREAD

**Issue by ptyagii** [confluentinc/confluent-kubernetes-examples#26]
Following secretRefs were missing when using [confluent-platform-production-mtls.yaml](https://github.com/confluentinc/confluent-kubernetes-examples/blob/master/security/production-secure-deploy/confluent-platform-production-mtls.yaml) file: 

```
11s         Warning   SecretRefIssue     connect/connect                      secretRef tls-connect not found
11s         Warning   SecretRefIssue     controlcenter/controlcenter     secretRef tls-controlcenter not found
11s         Warning   SecretRefIssue     kafka/kafka                               secretRef tls-kafka-external not found
11s         Warning   SecretRefIssue     ksqldb/ksqldb                           secretRef tls-ksqldb not found
11s          Warning   SecretRefIssue    kafka/kafka                                secretRef tls-kafka-internal not found
11s         Warning   SecretRefIssue     schemaregistry/schemaregistry   secretRef tls-schemaregistry not found
12s         Warning   SecretRefIssue     zookeeper/zookeeper             secretRef tls-zookeeper not found
```

I was able to install CP after creating the missing secrets for all the components. Can we please add the step to create the secrets for mtls authentication deployment?

**Comment by saicharana731** [comment]
hey @ptyagii you may create the secrets in a similar way as you have created tls-group1 for all the component specific secrets.

let pass the cmd for zookeeper which you can replicate for other components as well :

cfssl gencert -ca=$TUTORIAL_HOME/../../assets/certs/generated/ca.pem \
-ca-key=$TUTORIAL_HOME/../../assets/certs/generated/ca-key.pem \
-config=$TUTORIAL_HOME/../../assets/certs/ca-config.json \
-profile=server $TUTORIAL_HOME/../../assets/certs/zookeeper-domain.json | cfssljson -bare $TUTORIAL_HOME/../../assets/certs/generated/zookeeper

**Comment by MosheBlumbergX** [comment]
https://github.com/confluentinc/confluent-kubernetes-examples/tree/master/security/internal_external-tls_mtls_confluent-rbac
