### ISSUE TITLE
missing confluent-platform-security-deployment.png

### ISSUE THREAD

**Issue by MosheBlumbergX** [confluentinc/confluent-kubernetes-examples#5]
Looks like the hyper link to confluent-platform-security-deployment.png is broken on page: 

https://github.com/confluentinc/confluent-kubernetes-examples/tree/master/security/secure-authn-encrypt-deploy

**Comment by rohit2b** [comment]
Thanks @MosheBlumbergX for reporting this! I fixed this in the doc.
