### ISSUE TITLE
Getting permission denied message on RKE 1.1.19

### ISSUE THREAD

**Issue by Teju367** [confluentinc/confluent-kubernetes-examples#70]
I have deployed confluent-operator as per this document
https://docs.confluent.io/operator/current/co-quickstart.html

   --version, -v  print the version
[root@tfancbc-ibmdevel-1 kafka-pv]# kubectl get nodes
NAME            STATUS   ROLES               AGE   VERSION
10.101.216.91   Ready    controlplane,etcd   20d   v1.18.20
10.101.216.92   Ready    worker              20d   v1.18.20
10.101.216.93   Ready    worker              20d   v1.18.20
[root@tfancbc-ibmdevel-1 kafka-pv]# kubectl get pod
NAME                                  READY   STATUS             RESTARTS   AGE
confluent-operator-78674949c9-hc4v2   1/1     Running            0          30m
connect-0                             0/1     CrashLoopBackOff   8          29m
zookeeper-0                           0/1     CrashLoopBackOff   10         29m
zookeeper-1                           0/1     CrashLoopBackOff   10         29m
zookeeper-2                           0/1     CrashLoopBackOff   6          10m
[root@tfancbc-ibmdevel-1 kafka-pv]#

[root@tfancbc-ibmdevel-1 kafka-pv]# rke --version
rke version v1.1.19
[root@tfancbc-ibmdevel-1 kafka-pv]#

But while bringing up zookeeper I am getting below issue

[root@tfancbc-ibmdevel-1 kafka-pv]# kubectl logs zookeeper-2
+ /mnt/config/zookeeper/bin/run
===> User
uid=1001 gid=0(root) groups=0(root),1001
===> Load zookeeper operator scripts from path /mnt/config/zookeeper/bin
/mnt/config/zookeeper/bin/configure: line 13: /mnt/data/data/myid: Permission denied
[root@tfancbc-ibmdevel-1 kafka-pv]#

This is security context set in pod(default value)
  securityContext:
    fsGroup: 1001
    runAsNonRoot: true
    runAsUser: 1001

This the sc and pv details
[root@tfancbc-ibmdevel-1 kafka-pv]# kubectl get sc
NAME             PROVISIONER            RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
slow (default)   kubernetes.io/gce-pd   Delete          Immediate           false                  11d
[root@tfancbc-ibmdevel-1 kafka-pv]# kubectl get pv | grep confluent
data-zookeeper-1   10Gi       RWO            Retain           Bound      confluent/txnlog-zookeeper-0                        slow                    29m
data-zookeeper-2   10Gi       RWO            Retain           Bound      confluent/data-zookeeper-1                          slow                    29m
data-zookeeper-3   10Gi       RWO            Retain           Bound      confluent/data-zookeeper-2                          slow                    29m
log-zookeeper-1    10Gi       RWO            Retain           Bound      confluent/txnlog-zookeeper-2                        slow                    29m
log-zookeeper-2    10Gi       RWO            Retain           Bound      confluent/data-zookeeper-0                          slow                    29m
log-zookeeper-3    10Gi       RWO            Retain           Bound      confluent/txnlog-zookeeper-1                        slow                    29m

**Comment by ptyagii** [comment]
hey @Teju367 you may try disabling the podSecurityContext similar to https://github.com/confluentinc/confluent-kubernetes-examples/blob/master/security/openshift-security/confluent-platform-with-defaultSCC.yaml#L13-L14

**Comment by Teju367** [comment]
Thanks for your response!
