### ISSUE TITLE
Unused file in userprovided-tls_mtls_kafka-acls

### ISSUE THREAD

**Issue by domenicbove** [confluentinc/confluent-kubernetes-examples#72]
It appears the file kafka-client.txt within userprovided-tls_mtls_kafka-acls never gets used and can be removed. This is a very effective example btw, worked great!

Also the directory has a mix of hyphens and underscores, might want to standardize.

Another idea that could be worth mentioning is simply adding all the component principals to the super.users list

**Comment by domenicbove** [comment]
Actually it appears the c3 secret is not used either

**Comment by MosheBlumbergX** [comment]
@rohit2b  and I had a discussion a while back about the acls vs super user and ended up deciding about the ACLs in order to showcase which are needed in this deployment.
