### ISSUE TITLE
Typo in the container image name

### ISSUE THREAD

**Issue by huynconfluent** [confluentinc/confluent-kubernetes-examples#99]
https://github.com/confluentinc/confluent-kubernetes-examples/blob/af3ea4df4dc132bbad81f19be060463771cd9331/hybrid/clusterlink/mtls_source_cluster/zk-kafka-destination.yaml#L28

There is an extra "r" on the init container name for kafka deployment. This will cause an error when deploying on destination

**Comment by MosheBlumbergX** [comment]
fixed
